### ISSUE TITLE
Customizable Elytra (customizableelytra) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by falconfruitpunch1** [Hidoni/CustomizableElytra#18]
I am playing on a server with someone and we have the exact same mods installed, and the server has the same mods minus optifine. Their game is working fine, but mine crashes with the message, "Customizable Elytra (customizableelytra) encountered an error during the sided_setup event phase java.util.ConcurrentModificationException: null." The only difference is that the other person is playing on a different kind of computer. 
Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.1-1.0.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.0        |ENQUEUE_IM|Manifest: NOSIGNATURE
		customizableelytra-1.18-1.6.3.jar                 |Customizable Elytra           |customizableelytra            |1.18-1.6.3          |ERROR     |Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |ENQUEUE_IM|Manifest: NOSIGNATURE
		curious-armor-stands-1.18.1-4.0.0.jar             |Curious Armor Stands          |curious_armor_stands          |1.18.1-4.0.0        |ENQUEUE_IM|Manifest: NOSIGNATURE
		bedspreads-forge-1.18-5.1.0.4.jar                 |Bedspreads                    |bedspreads                    |1.18-5.1.0.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		farsight-1.18-1.5.jar                             |Farsight mod                  |farsight_view                 |1.18-1.5            |ENQUEUE_IM|Manifest: NOSIGNATURE
		potionbundles-1.18.1-1.1.jar                      |Potion Bundles                |potionbundles                 |1.1                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		fixedanvilrepaircost_1.18.1-1.7.jar               |Fixed Anvil Repair Cost       |fixedanvilrepaircost          |1.7                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.18.1-39.0.9-universal.jar                 |Forge                         |forge                         |39.0.9              |ENQUEUE_IM|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		expandability-5.0.0-forge.jar                     |ExpandAbility                 |expandability                 |5.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.4.2.jar                   |Curios API                    |curios                        |1.18.1-5.0.4.2      |ENQUEUE_IM|Manifest: NOSIGNATURE
		mutil-1.18.1-4.0.0.jar                            |mutil                         |mutil                         |4.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		thutcore-1.18.1-8.5.0.jar                         |Thut Core                     |thutcore                      |8.5.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		betterboats-1.1.4.jar                             |Better Boats                  |betterboats                   |1.1.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		parrying-1.18.1-2.3.jar                           |Parrying                      |parrying                      |2.3                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		awesomedungeon-1.1.4.jar                          |Awesome Dungeon               |awesomedungeon                |1.1.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		citadel-1.10.3-1.18.jar                           |Citadel                       |citadel                       |1.10.3              |ENQUEUE_IM|Manifest: NOSIGNATURE
		alexsmobs-1.14.4.jar                              |Alex's Mobs                   |alexsmobs                     |1.14.4              |ENQUEUE_IM|Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Quark-3.0-333.jar                                 |Quark                         |quark                         |3.0-333             |ENQUEUE_IM|Manifest: NOSIGNATURE
		smelt_raw_blocks-1.0.1.jar                        |Smelt Raw Blocks              |smelt_raw_blocks              |1.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE

**Comment by Hidoni** [comment]
Could you please upload the full crash log? It would help in figuring out what is actually going wrong :)

**Comment by falconfruitpunch1** [comment]
alright, 
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/31/21, 3:27 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.18.1-39.0.9-universal.jar%2378!:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:183) ~[forge-1.18.1-39.0.9-universal.jar%2378!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:553) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:569) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:547) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1254) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.9.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
-- MOD customizableelytra --
Details:
	Mod File: customizableelytra-1.18-1.6.3.jar
	Failure message: Customizable Elytra (customizableelytra) encountered an error during the sided_setup event phase
		java.util.ConcurrentModificationException: null
	Mod Version: 1.18-1.6.3
	Mod Issue URL: https://github.com/Hidoni/CustomizableElytra/issues
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.item.ItemProperties.register(ItemProperties.java:60) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.hidoni.customizableelytra.events.ClientEventHandler.handleClientLoading(ClientEventHandler.java:16) ~[customizableelytra-1.18-1.6.3.jar%2362!:1.18-1.6.3] {re:classloading}
	at com.hidoni.customizableelytra.CustomizableElytra.clientLoadingEvent(CustomizableElytra.java:47) ~[customizableelytra-1.18-1.6.3.jar%2362!:1.18-1.6.3] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.0.9.jar%2376!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.0.9.jar%2375!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1856270064 bytes (1770 MiB) / 3925868544 bytes (3744 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 56204.76
	Virtual memory used (MB): 15892.93
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 34
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 496.49
	OpenGlRenderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 20
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.1-1.0.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.0        |ENQUEUE_IM|Manifest: NOSIGNATURE
		customizableelytra-1.18-1.6.3.jar                 |Customizable Elytra           |customizableelytra            |1.18-1.6.3          |ERROR     |Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |ENQUEUE_IM|Manifest: NOSIGNATURE
		curious-armor-stands-1.18.1-4.0.0.jar             |Curious Armor Stands          |curious_armor_stands          |1.18.1-4.0.0        |ENQUEUE_IM|Manifest: NOSIGNATURE
		bedspreads-forge-1.18-5.1.0.4.jar                 |Bedspreads                    |bedspreads                    |1.18-5.1.0.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		farsight-1.18-1.5.jar                             |Farsight mod                  |farsight_view                 |1.18-1.5            |ENQUEUE_IM|Manifest: NOSIGNATURE
		potionbundles-1.18.1-1.1.jar                      |Potion Bundles                |potionbundles                 |1.1                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		fixedanvilrepaircost_1.18.1-1.7.jar               |Fixed Anvil Repair Cost       |fixedanvilrepaircost          |1.7                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.18.1-39.0.9-universal.jar                 |Forge                         |forge                         |39.0.9              |ENQUEUE_IM|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		expandability-5.0.0-forge.jar                     |ExpandAbility                 |expandability                 |5.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.4.2.jar                   |Curios API                    |curios                        |1.18.1-5.0.4.2      |ENQUEUE_IM|Manifest: NOSIGNATURE
		mutil-1.18.1-4.0.0.jar                            |mutil                         |mutil                         |4.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		thutcore-1.18.1-8.5.0.jar                         |Thut Core                     |thutcore                      |8.5.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		betterboats-1.1.4.jar                             |Better Boats                  |betterboats                   |1.1.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		parrying-1.18.1-2.3.jar                           |Parrying                      |parrying                      |2.3                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		awesomedungeon-1.1.4.jar                          |Awesome Dungeon               |awesomedungeon                |1.1.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		citadel-1.10.3-1.18.jar                           |Citadel                       |citadel                       |1.10.3              |ENQUEUE_IM|Manifest: NOSIGNATURE
		alexsmobs-1.14.4.jar                              |Alex's Mobs                   |alexsmobs                     |1.14.4              |ENQUEUE_IM|Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Quark-3.0-333.jar                                 |Quark                         |quark                         |3.0-333             |ENQUEUE_IM|Manifest: NOSIGNATURE
		smelt_raw_blocks-1.0.1.jar                        |Smelt Raw Blocks              |smelt_raw_blocks              |1.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: 47349a5c-5d2a-4e02-af5d-1db1d87f24fc
	FML: 39.0
	Forge: net.minecraftforge:39.0.9

**Comment by falconfruitpunch1** [comment]
also i tried removing optifine and the same thing happened

**Comment by Hidoni** [comment]
Looking at the stacktrace, this doesn't seem to actually be caused the mod itself, but by some other mod modifying Minecraft the ItemProperties class, it crashes in a function that the mod has no control over. How sure are you that you and your friend have no difference between your games? Are all the mod versions are the same down to the last and do you both have the same Forge version?

**Comment by falconfruitpunch1** [comment]
pretty sure, we both downloaded the same forge version today and i sent them the latest zip folder containing all mods that im using but i can check again

**Comment by falconfruitpunch1** [comment]
just confirmed that they are the exact same

**Comment by Hidoni** [comment]
That's pretty weird, if that's the case then you should both be crashing...
The only thing I can think of to diagnose this is to remove mods and see which one is causing the incompatibility..
Could you try removing half your mods (Not including this one), and seeing if it crashes? If it doesn't, try the other half and do the same. if it does crash, remove another half and repeat. If it's a crash caused from a change from one other mod interacting with this one, then this should quickly narrow down which one it is :)

**Comment by falconfruitpunch1** [comment]
alright so thanos method, got it. will report back

**Comment by falconfruitpunch1** [comment]
found the culprit! and it wasnt even a mod i cared about that much! thanks for all of your help!

**Comment by Hidoni** [comment]
Glad to hear it! Out of curiosity, what mod was it? I wanna check out what they did to cause the crash lol.

**Comment by falconfruitpunch1** [comment]
sorry for late reply, but the mod is bedspreads
